use crate::errors::OmvError;
use crate::sync::{
    PlanTargetResult, SyncContext, TargetSyncAdapter, plan_manifest_runtime, read_text_if_exists,
    replace_or_append_line, resolve_target_path,
};

#[derive(Debug, Default)]
pub struct CFamilySyncAdapter;

impl TargetSyncAdapter for CFamilySyncAdapter {
    fn language_key(&self) -> &'static str {
        "c-family"
    }

    fn plan(&self, context: &SyncContext<'_>) -> Result<PlanTargetResult, OmvError> {
        let manifest_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.manifest_path,
        );

        let manifest = match read_text_if_exists(&manifest_path)? {
            Some(content) if !content.trim().is_empty() => replace_or_append_line(
                &content,
                "set(OMV_VERSION",
                &format!("set(OMV_VERSION \"{}\")", context.version),
            ),
            _ => format!(
                "cmake_minimum_required(VERSION 3.16)\nproject({})\nset(OMV_VERSION \"{}\")\n",
                context.target.id, context.version
            ),
        };

        let runtime = format!(
            "/* Generated by omv. Do not edit manually. */\n#ifndef OMV_VERSION_H\n#define OMV_VERSION_H\n\n#define OMV_VERSION \"{}\"\n\n#endif\n",
            context.version
        );
        plan_manifest_runtime(context, self.language_key(), "c-cmake", manifest, runtime)
    }
}
