use crate::errors::OmvError;
use crate::sync::{
    PlanTargetResult, SyncContext, TargetSyncAdapter, plan_manifest_runtime, read_text_if_exists,
    replace_or_append_line, resolve_target_path,
};

#[derive(Debug, Default)]
pub struct GoSyncAdapter;

impl TargetSyncAdapter for GoSyncAdapter {
    fn language_key(&self) -> &'static str {
        "go"
    }

    fn plan(&self, context: &SyncContext<'_>) -> Result<PlanTargetResult, OmvError> {
        let manifest_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.manifest_path,
        );

        let manifest = match read_text_if_exists(&manifest_path)? {
            Some(content) if !content.trim().is_empty() => replace_or_append_line(
                &content,
                "// omv-version:",
                &format!("// omv-version: {}", context.version),
            ),
            _ => format!(
                "module {}\n\ngo 1.22\n// omv-version: {}\n",
                context.target.id, context.version
            ),
        };

        let runtime = format!(
            "// Generated by omv. Do not edit manually.\npackage omv\n\nconst Version = \"{}\"\n",
            context.version
        );
        plan_manifest_runtime(context, self.language_key(), "go-module", manifest, runtime)
    }
}
