use crate::errors::OmvError;
use crate::sync::{
    SyncContext, TargetSyncAdapter, read_text_if_exists, resolve_target_path, write_text,
};

#[derive(Debug, Default)]
pub struct JavaSyncAdapter;

impl TargetSyncAdapter for JavaSyncAdapter {
    fn language_key(&self) -> &'static str {
        "java"
    }

    fn sync(&self, context: &SyncContext<'_>) -> Result<(), OmvError> {
        let manifest_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.manifest_path,
        );
        let runtime_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.runtime_export_path,
        );

        let manifest = match read_text_if_exists(&manifest_path)? {
            Some(content) if !content.trim().is_empty() => {
                replace_or_insert_version_tag(&content, context.version)
            }
            _ => format!(
                "<project>\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>omv</groupId>\n  <artifactId>{}</artifactId>\n  <version>{}</version>\n</project>\n",
                context.target.id, context.version
            ),
        };
        write_text(&manifest_path, &manifest)?;

        let runtime = format!(
            "// Generated by omv. Do not edit manually.\npackage omv;\n\npublic final class Version {{\n    public static final String VALUE = \"{}\";\n\n    private Version() {{}}\n}}\n",
            context.version
        );
        write_text(&runtime_path, &runtime)?;

        Ok(())
    }
}

fn replace_or_insert_version_tag(content: &str, version: &str) -> String {
    let open = "<version>";
    let close = "</version>";

    if let Some(start) = content.find(open) {
        let value_start = start + open.len();
        if let Some(end_rel) = content[value_start..].find(close) {
            let end = value_start + end_rel;
            let mut output = String::new();
            output.push_str(&content[..value_start]);
            output.push_str(version);
            output.push_str(&content[end..]);
            return output;
        }
    }

    if let Some(insert_pos) = content.find("</project>") {
        let mut output = String::new();
        output.push_str(&content[..insert_pos]);
        output.push_str(&format!("  <version>{version}</version>\n"));
        output.push_str(&content[insert_pos..]);
        return output;
    }

    format!("{content}\n<version>{version}</version>\n")
}
