use crate::errors::OmvError;
use crate::sync::{
    SyncContext, TargetSyncAdapter, read_text_if_exists, replace_or_append_line,
    resolve_target_path, write_text,
};

#[derive(Debug, Default)]
pub struct PythonSyncAdapter;

impl TargetSyncAdapter for PythonSyncAdapter {
    fn language_key(&self) -> &'static str {
        "python"
    }

    fn sync(&self, context: &SyncContext<'_>) -> Result<(), OmvError> {
        let manifest_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.manifest_path,
        );
        let runtime_path = resolve_target_path(
            context.project_root,
            &context.target.root,
            &context.target.runtime_export_path,
        );

        let manifest = match read_text_if_exists(&manifest_path)? {
            Some(content) if !content.trim().is_empty() => replace_or_append_line(
                &content,
                "version =",
                &format!("version = \"{}\"", context.version),
            ),
            _ => format!(
                "[project]\nname = \"{}\"\nversion = \"{}\"\n",
                context.target.id, context.version
            ),
        };
        write_text(&manifest_path, &manifest)?;

        let runtime = format!(
            "# Generated by omv. Do not edit manually.\nOMV_VERSION = \"{}\"\n",
            context.version
        );
        write_text(&runtime_path, &runtime)?;

        Ok(())
    }
}
